GET https://localhost:3000

###

GET https://localhost:3000?manufacturer=bmw

###

GET https://localhost:3000?yearManufactured=2019

###

GET https://localhost:3000?color=yellow

###

GET https://localhost:3000?minEngineVolume=3.1

###

GET https://localhost:3000?maxEngineVolume=4

###

GET https://localhost:3000?minEngineVolume=1.2&maxEngineVolume=4.9

###

GET https://localhost:3000?minPrice=30000

###

GET https://localhost:3000?maxPrice=40000

###

GET https://localhost:3000?minPrice=30099&maxPrice=90000

###

POST https://localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2E3ZTFkN2RiZWFlMmNmNTdjM2RjYSIsImlhdCI6MTY2ODk3MzY5MiwiZXhwIjoxNjY5MDYwMDkyfQ.WJdDePGUMADUgWbGgqxvixgnxuig7Tw7DyTcz28zy-Y

{
    "name": "M5",
    "manufacturer": { "name": "BMW" },
    "yearManufactured": 2019,
    "engineVolume": 4.4,
    "price": 90000,
    "color": "Red"
}

###

GET https://localhost:3000/6376567aa5d0c9cabcd316a3

###

DELETE https://localhost:3000/637a451060e2fa1724338ef2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2E3ZTFkN2RiZWFlMmNmNTdjM2RjYSIsImlhdCI6MTY2ODk3MzY5MiwiZXhwIjoxNjY5MDYwMDkyfQ.WJdDePGUMADUgWbGgqxvixgnxuig7Tw7DyTcz28zy-Y

###

PUT https://localhost:3000/637a451060e2fa1724338ef2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2E3ZTFkN2RiZWFlMmNmNTdjM2RjYSIsImlhdCI6MTY2ODk3MzY5MiwiZXhwIjoxNjY5MDYwMDkyfQ.WJdDePGUMADUgWbGgqxvixgnxuig7Tw7DyTcz28zy-Y
Content-Type: application/json

{
    "color": "Green"
}