GET https://localhost:3000

###

GET https://localhost:3000?manufacturer=bmw

###

GET https://localhost:3000?yearManufactured=2019

###

GET https://localhost:3000?color=yellow

###

GET https://localhost:3000?minEngineVolume=1.0

###

GET https://localhost:3000?maxEngineVolume=5.2

###

GET https://localhost:3000?minEngineVolume=1.2&maxEngineVolume=4.3

###

GET https://localhost:3000?minPrice=4000

###

GET https://localhost:3000?maxPrice=12000

###

GET https://localhost:3000?minPrice=1999&maxPrice=13999

###

POST https://localhost:3000
Content-Type: application/json

{
    "name": "Mustang",
    "manufacturer": { "name": "Ford" },
    "yearManufactured": 2014,
    "engineVolume": 3.3,
    "price": 41000,
    "color": "Red"
}

###

GET https://localhost:3000/6376569ea5d0c9cabcd316a6

###

DELETE https://localhost:3000/637656b1a5d0c9cabcd316a9

###

PUT https://localhost:3000/637a451060e2fa1724338ef2
Content-Type: application/json

{
    "name": "GT500",
    "manufacturer": { "name": "Shelby" },
    "yearManufactured": 2016,
    "engineVolume": 3.5,
    "price": 45000,
    "color": "Blue"
}