GET https://localhost:3000

###

GET https://localhost:3000?manufacturer=shelby

###`

GET https://localhost:3000?yearManufactured=2019

###

GET https://localhost:3000?color=blue

###

GET https://localhost:3000?minEngineVolume=2

###

GET https://localhost:3000?maxEngineVolume=3

###

GET https://localhost:3000?minEngineVolume=1.2&maxEngineVolume=3

###

GET https://localhost:3000?minPrice=30000

###

GET https://localhost:3000?maxPrice=32000

###

GET https://localhost:3000?minPrice=30099&maxPrice=53999

###

POST https://localhost:3000
Content-Type: application/json

{
    "name": "Mustang",
    "manufacturer": { "name": "Ford" },
    "yearManufactured": 2014,
    "engineVolume": 3.3,
    "price": 41000,
    "color": "Red"
}

###

GET https://localhost:3000/6376569ea5d0c9cabcd316a6

###

DELETE https://localhost:3000/637656b1a5d0c9cabcd316a9

###

PUT https://localhost:3000/637a451060e2fa1724338ef2
Content-Type: application/json

{
    "name": "GT500",
    "manufacturer": { "name": "Shelby" },
    "yearManufactured": 2016,
    "engineVolume": 3.5,
    "price": 45000,
    "color": "Blue"
}